name: Made By oxIceBear

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/jagrosh/MusicBot/releases/download/0.3.9/JMusicBot-0.3.9.jar -OutFile jmusic.jar
    - name: Download config
      run: Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/e1spvl2obg5bbe5br3mnz/config.txt?rlkey=4xggfdaokwqbnx1qxfttkuuu5&dl=1" -OutFile "config.txt"
    - name: Start Jmusicbot
      run: java -Dnogui=true -jar jmusic.jar
